repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-yaml

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.0
  hooks:
  - id: check-github-workflows

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
    additional_dependencies:
        # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
        # and checks these with shellcheck. This is arguably its most useful feature,
        # but the integration only works if shellcheck is installed
    - github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0

- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: v1.2.2
  hooks:
  - id: zizmor
